- hello.html
- scripts/content.js
This new version use a 3rd party server to store votes and avoid querying amazon directly.
> 3rd party srv

- .gitignore
- popup/popup.css
- scripts/bootloader.js
- scripts/tile.js
and display in local time, were appropriate (Bookmark alert).  the massive list of changes in bootloader.js are only format, vscode updated that when I formatted my code into place... the only code change is at 119
> Updated a few datetime values to work with GMT input

- popup/homepage.html
> Fixed misspelling in discord server link

- popup/homepage.html
- popup/popup.css
💡Scrolling should be separate from the tabs so the user can navigate menus easier.
⚠all-options relies on hardcoded values
📑someone should find a way to not rely on these values incase the height changes on the body, header or tab in the ul
IDK about the compatibility on mobile devices
Also my prettier plugin changed a bunch of white space. I can re-do this on a fresh copy if needed.
> Better UX experience for scrolling

- popup/homepage.html
- popup/homepage.js
- popup/popup.css
- resource/css/icon.css
- resource/css/modal.css
- resource/css/tabs.css
- scripts/ModalMgr.js
- scripts/bootloader.js
Updated Modal class to use a named ID instead of
numeric, to aid in preventing repeated instances
of a dialog box from being opened.
Updated CSS to support system based light/dark
mode in the modals, as well as the extension
window itself.
Added a click to copy function on the crypto
addresses
A few formatting updates, imposed by VS Code :)
> CSS updates/Modal Updates & click function for crypto

- resource/css/modal.css
- scripts/bootloader.js
- scripts/preboot.js
Added some code to pull the chrome.storage.local details into the existing debug window, using the existing showruntime fuction.  
Correct the function name on of the calls.
> Updates to debug output

- resource/css/modal.css
Missed the .content ul for the version popup
> Minor fix for dark mode in the version popup

- scripts/HiddenListMgr.js
- scripts/preboot.js
Hoping these fix the issues with garbage collection... I tested the debug in Firefox and it worked correctly!
> Fixes for garbage collection and debug in firefox

- scripts/HiddenListMgr.js
- scripts/Template.js
- scripts/bootloader.js
- scripts/grid.js
- scripts/preboot.js
I pulled all the changes out and pushed them here so as to not confuse, let me know if you find anything wrong
> Minor changes, pulled from update for notification window

- page/notifications.js
Checks for an existing ASIN before posting to the monitor
> Notifications monitor dup check

- page/notifications.css
- page/notifications.js
- scripts/ModalMgr.js
- scripts/bootloader.js
- view/notification_monitor.html
Updated notification monitor to display ETV is known
Updated display box to highlight differently if ETV is 0.00 (supports dark mode)
Modified the runtime.sendMessage, to only pass vineDomain
Added the http://amazon. part to the template, can't use the URL of the notification page
> Updated notifications monitor to show ETV if known

- page/review_management.css
- page/reviews_manage.html
- page/reviews_manage.js
- page/reviews_templates.html
- page/reviews_templates.js
- scripts/review.js
Added some input sanitizing
still need to add css to /create-review
> Updated review pages with CSS

- scripts/inj.js
* swapped the replacement of characters to use VH# as the text at the end as the actual underlying issue is not the characters but the end characters cannot be a special character.
* cleaned up code to use maps, optional properties, and a bunch of other changes, formatted with prettier, reduced amount of code by 25+% 😺
> Infinite Loading Refactor / Improvements

- resource/css/vinehelper.css
This is just CSS updates to the vinehelper css file
> Updated CSS values to a common theme structure

- page/notifications.css
- page/notifications.js
Here are the modifications for Issue #71
> Modifications to notifications to add in keyword matching

- page/reviews_manage.html
- page/reviews_manage.js
- page/reviews_templates.html
- page/reviews_templates.js
- resource/css/vinehelper.css
- scripts/review.js
- view/review_toolbar.html
- Updated toolbar on reviews page --Common style
--No Saved Templates message if you have none
- Reviews & Templates pages --Tempate page, moved message next to buttons
--Review page, moved message below text boxes
--Action sections now hide if no reviews or templates
- Css updates to support the ? page in the popup -- more cleanup to unify css
> Review process updates

- resource/css/vinehelper.css
- scripts/bootloader.js
Background color of the account sections, when in dark mode, is the same as the
darkmode text color, set to light mode, off black color statically.
> Small fix for account stats

- resource/css/vinehelper.css
Theme's just so I don't loose them and I don't get behind :)
Also as mentioned I am using CSS Alphabetize to order the CSS, so the large changes are just that, no change to overall CSS function here...just adding the colors and the theme-X classes
> CSS Theme, part 1

- page/notifications.js
- page/reviews_manage.js
Also fixed some eslint error on Object.prototype.hasOwnProperty.call
> Fix for Time on Notifications Monitor

- resource/css/grid.css
item-highlight-alert <-- this was already in the vinehelper.css
> Fix alert border issue

- page/notifications.js
Fixed the typo in notifications.js file that was causing issues.
> fixed Typo

- scripts/tile.js
refactored code to account for NaN dates
> Fix for this.setDateAdded

- package.json
- resource/css/vinehelper.css
- scripts/review.js
- scripts/tile.js
- view/review_toolbar.html
Updated reviews, showing message now instead of an alert, also near the save button.
updated package.json, lint error with *.{js} said it needed to be *.js
exact error message
[info] ⚠ Detected incorrect braces with only single value: `*.{js}`. Reformatted as: `*.js`
Further streamlined the timeSince function, updated version was slower than original
> Review updates, quality of life

- page/notifications.js
- popup/homepage.html
- popup/homepage.js
- scripts/preboot.js
Add the option to apply hide keywords to the notifications monitor tab.
> Add option to apply hide keywords to notifications monitor tab

- page/notifications.js
- popup/homepage.html
- popup/homepage.js
- scripts/preboot.js
- view/notification_monitor.html
Add option to hide new notifications with the same image_url as notifications already present in the monitor tab.
Re-order some of the logic for performance.
> add image_url based notification deduplication

- scripts/bootloader.js
Adds code for the Expermental Modal Plugin that allows the user to navigate through items by using the keyboards arrow keys. Works only when the experimental feature has been enabled _(General > Experimental)_ and when the Product Details modal is open, to prevent accidental clicks.
> FEATURE: Modal Navigator as part of the extension

- .gitignore
- page/settings_keybindings.tpl.html
- page/settings_loadsave.js
- resource/css/main.css
- scripts/bootloader.js
- scripts/grid.js
- view/widget_hideall.html
Combined hide all and go to next page operation into a single click action to speed navigation
> Add Hide All and go to next page functionality

- feature_request.yml
> Create one issue form for feature requests and enhancements

- manifest.json
- scripts/bootloader.js
- scripts/vh_service_worker.js
Not ready to merge, I still need to update firefox and chrome manifests
> added right click menu to add hide and highlight keywords

- scripts/NotificationMonitor.js
- view/notification_monitor_header.html
For your consideration...
- If the Sort type is `date` there are no changes to the current functionality (defaults to this type)
- If the Sort type is `price` it will append new items to the end of the queue until a price is loaded, 
- When the price is loaded, it will sort all items by price
As discussed on Discord, it also includes the following...
- Improved performance via in-memory sort
- Remembers all User selected UI settings (using chrome.storage for better sandboxing)
> Add Notification Monitor Sorting

- scripts/NotificationMonitor.js
- scripts/SettingsMgr.js
- view/notification_monitor_header.html
> Auto truncate options

- resource/css/icon.css
- scripts/NotificationMonitor.js
- scripts/vh_service_worker.js
- Fixed another slow truncate bug
- Maintained scroll position for several cases
- Refactored item removal
- Allow toggling pinned state
- Fix contextMenu create bug
- Fix bug where window navigates to hash when clicking an icon
- when clicking near an icon (still inside the `<a>`) but not exactly on the icon (affected transparent areas too)
> Slow truncation, scroll position, pinned toggle state

- scripts/NotificationMonitor.js
Added boolean to check to see if the shift key is pressed with the button click event.
> Added Shift key press to See Details

- .eslintrc.json
- .gitignore
- docs/ARCHITECTURE.md
- docs/DEPENDENCY_INJECTION_MIGRATION.md
- docs/DI_IMPLEMENTATION_ROADMAP.md
- docs/README.md
- package.json
- scripts/SettingsMgrCompat.js
- scripts/SettingsMgrDI.js
- scripts/bootloader.js
- scripts/infrastructure/DIContainer.js
- scripts/infrastructure/README.md
- scripts/infrastructure/SettingsFactory.js
- scripts/infrastructure/StorageAdapter.js
- tests/infrastructure/DIContainer.test.js
- tests/infrastructure/StorageAdapter.test.js
> refactor: introduce dependency injection foundation for improved architecture

- page/settings.css
- page/settings_notifications.tpl.html
- scripts/ui/templates/widget_tilesize.html
This PR addresses multiple accessibility issues and CSS warnings to improve the user experience for all users, particularly those using assistive technologies.
- **Added aria-labels to play buttons** in settings_notifications.tpl.html
- All four play buttons now have descriptive labels for screen readers
- Labels describe which notification sound will be played
- **Fixed form label associations** in widget_tilesize.html
- Corrected duplicate `for` attributes on labels
- Added matching `id` attributes to all input elements
- Ensures proper label-input associations for screen readers
- **Added screen reader support**
- Added `.sr-only` CSS class for visually hidden but screen reader accessible content
- Applied to dual range slider labels for better accessibility
- **Fixed vendor prefix …
> fix: Improve accessibility and fix CSS warnings

- docs/ARCHITECTURE.md
- docs/FUTURE_IMPROVEMENTS.md
- docs/MEMORY_LEAK_FIXES.md
- docs/README.md
- pr-description-memory-leaks.md
- scripts/notifications-monitor/coordination/MasterSlave.js
- scripts/notifications-monitor/core/NotificationMonitor.js
- scripts/notifications-monitor/services/ItemsMgr.js
- scripts/notifications-monitor/stream/ServerCom.js
- scripts/notifications-monitor/stream/Websocket.js
This PR addresses critical memory leaks identified through Chrome memory profiling and fixes count synchronization issues during bulk operations. The changes reduce memory usage from 709 KB to ~420 KB (40% reduction) and ensure accurate item counts during bulk loading and clearing operations.
1. **Fixed Critical Interval Leaks**
- `MasterSlave.js`: Fixed uncleared 1-second interval (86,400 executions/day)
- Added `#keepAliveInterval` property to track interval ID
- Implemented `destroy()` method to clear interval on cleanup
- `ServerCom.js`: Fixed uncleared 10-second interval (8,640 executions/day)
- Added `destroy()` method to clear intervals
- Fixed double JSON stringification in data buffering
2. **WebSocket Event Handler Cleanup**
- `Websocket.js`: Converted anonymous functions to …
> Fix Memory Leaks and Count Synchronization Issues in VineHelper Notification Monitor

- docs/CSP_FIX.md
- docs/MEMORY_LEAK_FIXES.md
- docs/README.md
- manifest.json
- manifest_chrome.json
- manifest_firefox.json
- manifest_ios.json
- page/settings.html
- page/settings.js
- scripts/notifications-monitor/core/MonitorCore.js
- scripts/notifications-monitor/core/NotificationMonitor.js
- scripts/notifications-monitor/services/GridEventManager.js
- scripts/notifications-monitor/services/ItemsMgr.js
- scripts/notifications-monitor/services/NoShiftGrid.js
- scripts/notifications-monitor/stream/Websocket.js
- scripts/ui/components/Grid.js
- tests/manifest-csp.test.js
- tests/notifications-monitor/services/GridEventManager.test.js
This PR addresses two critical issues:
1. **Content Security Policy (CSP) errors** preventing the extension from loading in Chrome
2. **Placeholder synchronization issues** during concurrent filter changes and server updates
**Problem**: Chrome was rejecting the extension with:
```
'content_security_policy.extension_pages': Insecure CSP value "https://appleid.cdn-apple.com" in directive 'script-src'.
```
**Solution**: Implemented platform-specific CSP configurations:
- ✅ Removed `https://appleid.cdn-apple.com` from Chrome/Firefox manifests
- ✅ Kept it in Safari/iOS manifest where it's allowed
- ✅ Added dynamic script loading for Safari only
- ✅ Implemented graceful fallback with browser-specific messages
**Problem**: Placeholders would disappear when changing filters while bulk loading …
> Fix CSP errors and placeholder synchronization issues
